import type { ReactNode } from 'react';
import type { Metadata } from 'next';
import { Theme } from '@radix-ui/themes';
import { getServerSession } from 'next-auth';
import SessionProvider from '@/components/auth/SessionProvider';

import { redirect } from 'next/navigation';

import { authOptions } from '@/lib/auth';
import { dashboardConfig } from '@/config/dashboard';
import getCurrentUser from '@/lib/session';
import MainNav from '@/widgets(app)/MainNav';
import DashboardNav from '@/widgets(app)/Nav';
import SiteFooter from '@/widgets(app)/SiteFooter';
import Toaster from '@/components/ui/Toaster';
import UserAccountNav from '@/widgets/UserAccountNav';

import '@radix-ui/themes/styles.css';
import '../../globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const session = await getServerSession(authOptions);
  const user = await getCurrentUser();

  if (!user) {
    redirect(authOptions?.pages?.signIn || '/login');
  }

  return (
    <html lang='en'>
      <body>
        <SessionProvider session={session}>
          <Theme appearance='light' accentColor='red' radius='medium'>
            <div className='flex min-h-screen flex-col space-y-6'>
              <header className='sticky top-0 z-40 border-b bg-background'>
                <div className='container flex h-16 items-center justify-between py-4'>
                  <MainNav items={dashboardConfig.mainNav} />
                  <UserAccountNav
                    user={{
                      name: user.name,
                      image: user.image,
                      email: user.email,
                    }}
                  />
                </div>
              </header>
              <div className='container grid flex-1 gap-12 md:grid-cols-[200px_1fr]'>
                <aside className='hidden w-[200px] flex-col md:flex'>
                  <DashboardNav items={dashboardConfig.sidebarNav} />
                </aside>
                <main className='flex w-full flex-1 flex-col overflow-hidden'>
                  {children}
                </main>
              </div>
              <SiteFooter className='border-t' />
            </div>
            <Toaster />
          </Theme>
        </SessionProvider>
      </body>
    </html>
  );
}
